### ISSUE TITLE
后端好像出问题了

### ISSUE THREAD

**Issue by leon-zym** [Nick930826/daily-cost#2]
大佬你好，我准备跟着这个项目练手Vue3。
我看axios.js里面api的地址是47.99.134.126:7008，不知道是您关闭了后端服务还是哪里出了问题，现在发现注册和登录功能似乎都无法使用，一直返回code: 500。
因为还处于前端的学习阶段，暂时没有能力自己构建后端服务，mock数据也比较吃力，所以希望大佬可以修复一下后端服务，谢谢！！

**Comment by Nick930826** [comment]
@Leon-zym 已修复
